### ISSUE TITLE
Ability to Set "Child Pages" Tab as Default

### ISSUE THREAD

**Issue by purplespider** [micmania1/silverstripe-lumberjack#10]
Currently the gridfield of pages appears in a secondary tab that comes after the Main Content tab.

I'm a strong believer that when a user clicks on a News Holder page they should immediately see the grid field of News Articles. Rather than having them hidden in another tab. 99% of the time someone clicking on the News Holder page is wanting to add/edit a News Article, and not change the News Holder Content or Title, for example.

I understand not every use case will want it this way but can a change please be made so that this is either configurable or overwritable?

The line in question is https://github.com/micmania1/silverstripe-lumberjack/blob/1.0/code/extensions/Lumberjack.php#L52 

I believe that as "insertAfter" has been explicitly used, it's not possible to overwrite this from the Holder page. 

I think we've spoken about this before (in Blogger) but I want to bring it up again as Blogger just used addFieldToTab(), rather than insertAfter(), meaning it could be overridden from the News Holder by using an insertBefore() in beforeUpdateCMSFields().

Possible solutions:
1. Change [insertAfter()](https://github.com/micmania1/silverstripe-lumberjack/blob/1.0/code/extensions/Lumberjack.php#L52) to insertBefore() :)
2. Make a config option that allows developers to choose between the two.
3. Use addFieldToTab() rather than insertAfter(), to allow users to override it in their Holder page.

**Comment by purplespider** [comment]
The new SilverStripe Blog module that is based on Lumberjack has gone for option 1 (insertBefore): https://github.com/silverstripe/silverstripe-blog/pull/223

Are you happy to also go forward with this for Lumberjack?

**Comment by lerni** [comment]
I would prefer if you could set the tab lumberjack shows the GridField on including "Main".
More and more I arrange fields "tab-less", top-down in the same order as they appear on the page - with split-mode (cms/preview) this is super nice. It would be cool if there is a way to have the GF on Root.Main. ATM I cannot see a way to do so. cc @assertchris

**Comment by purplespider** [comment]
I know this module has moved and that this repo is no longer being updated, but in case anyone comes across this request, the current solution appears to be to do it the way the official Blog module does: by extending Lumberjack:

**CustomLumberjack.php**

```
<?php
class CustomLumberjack extends Lumberjack {

    public function updateCMSFields(FieldList $fields) {
        $excluded = $this->owner->getExcludedSiteTreeClassNames();
        if(!empty($excluded)) {
            $pages = SiteTree::get()->filter(array(
                'ParentID' => $this->owner->ID,
                'ClassName' => $excluded
            ));
            $gridField = new GridField(
                "ChildPages",
                $this->getLumberjackTitle(),
                $pages,
                $this->getLumberjackGridFieldConfig()
            );

            $tab = new Tab('ChildPages', $this->getLumberjackTitle(), $gridField);
            $fields->insertBefore($tab, 'Main');
        }
    }

}
```

Note the last line, in this example I've changed it from `insertAfter` to `insertBefore`, but you could easily adjust it to put the GridField in any tab.

Then instead of adding `Lumberjack` as the extension to your page, you'd add `CustomLumberjack`.
