### ISSUE TITLE
Renaming Tab

### ISSUE THREAD

**Issue by lexandclo** [micmania1/silverstripe-lumberjack#11]
Hi 
Ive installed the add-on, and all is good,

One thing, how can we rename the tab from 'Child Pages' to something else?

Thanks

**Comment by micmania1** [comment]
You can create a getLumberjackTitle() method in your Page which returns the title.
See: https://github.com/micmania1/silverstripe-lumberjack/blob/1.0/code/extensions/Lumberjack.php#L96

Example:

```
class Blog extends Page {

    private static $extensions = array(
        'Lumberjack',
    );

    public function getLumberjackTitle() {
        return 'BlogPosts';
    }

}
```

**Comment by RuthAdele** [comment]
I thought I might add for the record, if you are doing this via an extension, you can use the following code to change the name and placement of the tab:

```
class MyExtension extends DataExtension  {

    public function updateCMSFields(FieldList $fields) {
        if ($childPages = $fields->fieldByName('Root.ChildPages')) {
            $fields->removeByName('ChildPages');
            $childPages->setTitle('MyNewTabName');
            $fields->insertBefore($childPages, 'Main');
        }
    }
}
```

**Comment by WoodrowShigeru** [comment]
Isn't it `$fields->insertBefore('Main', $childPages);`? I think the `$name` (where) comes before the `$item` (what).
