### ISSUE TITLE
Orphans cause explosions

### ISSUE THREAD

**Issue by assertchris** [micmania1/silverstripe-lumberjack#17]
While using this with Blog, following these steps causes an exception:
- Create (draft) Blog.
- Add BlogPost(s).
- Delete Blog.
- 'SPLOSIONS!

![screen shot 2015-04-17 at 4 45 18 pm](https://cloud.githubusercontent.com/assets/200609/7196246/3f0dea30-e522-11e4-898b-49f23d24b145.png)

I'm working on a PR. Just wanted to point it out here first!

**Comment by assertchris** [comment]
Downstream issue apparently...

**Comment by micmania1** [comment]
Best. Title. Ever.
