### ISSUE TITLE
GridFieldSiteTreeAddNewButton::getAllowedChildren() must be an instance of SiteTree

### ISSUE THREAD

**Issue by MatMorrisParker** [micmania1/silverstripe-lumberjack#25]
With lumberjack installed for a blog, and when trying to create a new user, I receive the following error:

"AH01215: PHP Catchable fatal error:  Argument 1 passed to GridFieldSiteTreeAddNewButton::getAllowedChildren() must be an instance of SiteTree, null given, called in ./silverstripe-lumberjack-1.1/code/forms/gridfield/GridFieldSiteTreeAddNewButton.php on line 38 and defined in ./silverstripe-lumberjack-1.1/code/forms/gridfield/GridFieldSiteTreeAddNewButton.php on line 17"

**Comment by Spambanjo** [comment]
I'm getting the same issue, did you ever find a fix for this?

**Comment by MatMorrisParker** [comment]
Unfortunately not - the issue still exists for me.

## 

*\* Consider the environment. Please don't print this e-mail unless you
really need to. **

**Comment by pdelany** [comment]
Am working on a SS3.1 -> 3.2.x upgrade and have run into the same issue.

**Comment by Spambanjo** [comment]
I just posted a temporary fix for this here:
http://www.silverstripe.org/community/forums/all-other-modules/show/104785#post412809

**Comment by pdelany** [comment]
Thanks Spambanjo - I see you modified the blog module - do you know if the issue lies in the blog module per se or lumberjack?

**Comment by Spambanjo** [comment]
I think something was added to Lumberjack which wasn't expected by the Blog module. I've submitted a bug report to the Blog authors as I believe it will be the Blog which will have to be modified in the long run.
https://github.com/silverstripe/silverstripe-blog/issues/375

**Comment by micmania1** [comment]
If this is still an issue could you please raise it at https://github.com/silverstripe/silverstripe-lumberjack where this module is now maintained? Thanks.

**Comment by pdelany** [comment]
Thanks micmania1 - I can confirm that the issue was resolved for me when using the official repo - guess I didn't look hard enough! ;)

**Comment by micmania1** [comment]
Good to hear :)
