### ISSUE TITLE
SS 3.2.0 problem with Lumberjack

### ISSUE THREAD

**Issue by t3hn0** [micmania1/silverstripe-lumberjack#26]
I have simple example of two PHP classes (parent and child) for news. Everything worked fine until I upgraded Silverstripe to version 3.2.0.
Lumberjack extends Hierarchy class. Hierarchy class forces creation of database table "NewsListPage" with field "ParentID", although no additional fields are defined in parent class. Problem is that ParentID already exists in SiteTree database table. So now we have two "ParentID" fields for "NewsListPage". Hierarchy changes in CMS work fine, but Link method doesn't work. It took me some time to debug this issue.

YAML:
`ListNewsPage:
  extensions:
    - Lumberjack`

Parent class (NewsListPage.php):
`<?php
class NewsListPage extends Page {
    private static $lumberjack_allowed_children = array('NewsPage');
}
class NewsListPage_Controller extends Page_Controller{
}
?>`

Child class (NewsPage.php):
`<?php
class NewsPage extends Page{
    private static $lumberjack_allowed_children = array();
    private static $show_in_sitetree = false;
}
class NewsPage_Controller extends Page_Controller{
}
?>`

**Comment by micmania1** [comment]
@t3hn0 thanks for reporting but this module is no longer maintained. The module can now instead be found at https://github.com/silverstripe/silverstripe-lumberjack/

Can you try upgrading to that module and if the problem persists, raise an issue there?
