### ISSUE TITLE
Lumberjack and Translatable: Locale is always set to default locale when adding new page

### ISSUE THREAD

**Issue by sebastiand** [micmania1/silverstripe-lumberjack#27]
When using Translatable module, the "Add New Page" Button in Lumberjack always creates a new page in the default_locale instead of the current_locale.
1. The locale in the URL is correct (it shows the current_locale - e.g.it says "?locale=de_DE"), the SiteTree that is shown on the left is also correct (shows the SiteTree of the current_locale) and using the `Translatable::get_current_locale()` function returns also the correct current_locale
2. The `Locale` field in the CMS form of the new page (`<input name="Locale" ... />`) always shows the default_locale (e.g. 'en_US')
3. When the page is saved it has a ID, ParentID, etc. of the current_locale sitestree structure, but a Locale that points to the default_locale. Because of this invalid setting (ParentID and Locale do not match) the page never shows up in any SiteTree (not in the default_locale nor in the current_locale)

I did not find anything in the `GridFieldSiteTreeAddNewButton` that could cause the locale to be set to the default_locale.

When I add the same Page via "Add New Page" of the SiteTree everything is fine...

I only found an ugly workaround, by setting the current_locale in `onBeforeWrite()` on my Page objects via extension:

``` php
class PageLumberjackLocaleFixExtension extends DataExtension {

    public function onBeforeWrite() {
        parent::onBeforeWrite();
        if(
            $this->owner->hasExtension('Translatable') &&
            $this->owner->parent->hasExtension('Lumberjack')
        ) {
            $locale = Translatable::get_current_locale();
            if ($this->owner->Locale !== $locale)
                $this->owner->Locale = $locale;
        }
    }
}
```

Adding the Extension to SiteTree to target all descendants that have the Lumberjack extension applied:

``` yml
SiteTree:
  extensions:
    # add fix for setting the correct Locale when page is added via Lumberjack add-on
    - PageLumberjackLocaleFixExtension
```

**Comment by micmania1** [comment]
@sebastiand thanks for reporting but this module has now moved and is maintained over at https://github.com/silverstripe/silverstripe-lumberjack.

This issue has been fixed over there https://github.com/silverstripe/silverstripe-lumberjack/pull/32
