### ISSUE TITLE
Make Child Pages sortable (by date or manual sort)

### ISSUE THREAD

**Issue by camfindlay** [micmania1/silverstripe-lumberjack#3]
Would be good to be able to set a config which orders Pages under lumberjack control sortable by a date (show newest Pages first in the gridfield), or enable some interface to change the order of the pages (sortable gridfield?).

Not having the pages on site tree means they are not sortable by drag and drop anymore.

**Comment by micmania1** [comment]
The pages are currently ordered by {ClassName}.default_sort if that helps.

**Comment by camfindlay** [comment]
Nice one, I didn't have a specific use in mind was thinking more along generic functionality lines. That is handy to know though :+1:

**Comment by phil-quinn** [comment]
Actually, that may not be correct. The pages are sorted as normal SiteTree pages, since you grab all the SiteTree items that are children of the holder page for display in the GridField. It does not use the default_sort set on the class for the children you are displaying.

I think you could fix this by doing a little introspection and pre-sorting the $pages DataList in Lumberjack.php.  Although this could also be problematic if you were allowing more than one class to be displayed in the list.

Maybe an additional configuration somewhere?

Would you like me to take a stab at this as a pull request?

Thanks!

**Comment by purplespider** [comment]
The ability to specify the sort order is pretty essential, especially when using Lumberjack for a news page holder. It would be great to see this capability, or at least some way to be able to override the default.

**Comment by micmania1** [comment]
The GridField data is populated here: https://github.com/micmania1/silverstripe-lumberjack/blob/1.0/code/extensions/Lumberjack.php#L40

@phil-quinn It would be great if you could have a go. I'm not sure when i'd be able to get around to it.

The main problem would be that all records displayed in the gridfield would have to all include the same column. 

I think the solution would be to add a getDefaultSort() method to Lumberjack which can be overridden in the 'holder' class. See how its done for title and config here: https://github.com/micmania1/silverstripe-lumberjack/blob/1.1/code/extensions/Lumberjack.php#L96

**Comment by terryapodaca** [comment]
Am I way off in assuming $Children.sort(Created DESC)?

**Comment by purplespider** [comment]
#16 provides a solution to this. @micmania1: Is it suitable? Or any adjustments required?

**Comment by mylesthedev** [comment]
Bump! Been a year since this has been submitted... It's used in quite a few default SilverStripe modules now and sorting is quite often required.

Was the pull request above ok to be merged?

**Comment by micmania1** [comment]
@mediabeastnz this module has moved over to https://github.com/silverstripe/silverstripe-lumberjack and there's a pull request: https://github.com/silverstripe/silverstripe-lumberjack/pull/11

There's a bit of feedback on the PR so if that's addressed and a new PR is submitted then it can be merged.
